import { test, expect, _electron as electron, type ElectronApplication } from '@playwright/test';
import path from 'node:path';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fixture, tempDirectory } from '../helpers';
let application: ElectronApplication;
test.afterEach(async () => { if (application) await application.close(); });
test('Electron: projetos, consulta Git real, histórico, validações e fronteira IPC', async () => {
  const f = await fixture(); const data = path.join(f.root, 'electron-data'); await mkdir(data);
  await writeFile(path.join(data, 'settings.json'), JSON.stringify({ roots: [f.root] }));
  const env: Record<string, string> = Object.fromEntries(Object.entries(process.env).filter((entry): entry is [string, string] => typeof entry[1] === 'string' && entry[0] !== 'ELECTRON_RUN_AS_NODE'));
  application = await electron.launch({ args: [path.resolve('.')], env: { ...env, RAMOS_TEST_DATA: data } });
  const page = await application.firstWindow(); await page.waitForLoadState('domcontentloaded');
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await expect(page.getByRole('heading', { name: 'Seus projetos', exact: true })).toBeVisible();
  await page.getByRole('button', { name: /work.*Abrir projeto/ }).click();
  await expect(page.getByRole('heading', { name: 'Criar / Alterar ramo', exact: true })).toBeVisible();
  await expect(page.locator('.branch-badge')).toContainText(f.source);
  await page.getByRole('button', { name: /^Projetos/ }).click();
  await expect(page.getByLabel('Buscar projeto')).toBeHidden(); await expect(page.locator('.project.selected')).toContainText('work');
  await page.getByRole('button', { name: /^Projetos/ }).click(); await expect(page.getByLabel('Buscar projeto')).toBeVisible();
  await expect(page.getByRole('radio')).toHaveCount(3);
  await page.getByLabel('Ramo', { exact: true }).fill('feature/nova-tela');
  await expect(page.getByRole('button', { name: 'Criar ramo e trocar →' })).toBeVisible(); await expect(page.getByLabel('A partir de')).toHaveValue(f.source);
  await page.getByLabel('Ramo', { exact: true }).fill('dev');
  await expect(page.getByRole('button', { name: 'Trocar ramo →', exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: /Executar pman/ })).toHaveCount(0); await expect(page.getByLabel('A partir de')).toHaveCount(0);
  await page.getByLabel('Criação dinâmica de ramos').check();
  await page.getByLabel('Nome do ramo 1').fill('lote/um'); await page.getByRole('button', { name: '+ Adicionar ramo' }).click();
  await page.getByLabel('Nome do ramo 2').fill('lote/dois'); await page.getByLabel('A partir de (2)').fill('lote/um');
  await expect(page.getByRole('button', { name: 'Criar 2 ramos →' })).toBeEnabled();
  await page.getByLabel('Nome do ramo 2').fill('dev'); await expect(page.getByText('Esse ramo já existe.')).toBeVisible();
  await page.getByLabel('Criação dinâmica de ramos').uncheck(); await expect(page.getByLabel('Ramo', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '⚙ Configurações' }).click();
  const usePman = page.getByLabel('Usa pman'); await expect(usePman).not.toBeChecked(); await usePman.check();
  await expect.poll(async () => JSON.parse(await readFile(path.join(data, 'settings.json'), 'utf8')).usePman).toBe(true);
  await page.getByRole('button', { name: 'Criar / Alterar ramo', exact: true }).click(); await page.getByLabel('Ramo', { exact: true }).fill('dev');
  await expect(page.getByRole('button', { name: 'Trocar ramo e instalar →' })).toBeVisible(); await expect(page.getByRole('button', { name: /Executar pman/ })).toBeVisible();
  await page.getByRole('button', { name: '⚙ Configurações' }).click(); await usePman.uncheck();
  await expect.poll(async () => JSON.parse(await readFile(path.join(data, 'settings.json'), 'utf8')).usePman).toBe(false);
  await page.getByRole('button', { name: 'Criar pull request', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Remoto não é do Azure DevOps' })).toBeVisible();
  await page.getByRole('button', { name: 'Histórico', exact: true }).click();
  await expect(page.getByRole('button', { name: /Segunda alteração/ })).toBeVisible();
  await page.getByRole('button', { name: /Segunda alteração/ }).click();
  await expect(page.locator('.diff')).toContainText('+origem');
  await page.getByRole('button', { name: 'Cherry-pick', exact: true }).click();
  await expect(page.getByLabel('Destino 2 · opcional')).toBeDisabled();
  await page.getByLabel('Ramo de origem', { exact: true }).fill(f.source);
  await page.getByRole('button', { name: 'Carregar commits', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Selecionar Primeira alteração' }).check();
  await page.getByLabel('Destino 1 · obrigatório').fill('main');
  await expect(page.getByLabel('Destino 2 · opcional')).toBeEnabled();
  await page.getByLabel('Destino 2 · opcional').fill('dev');
  await expect(page.getByLabel('Destino 3 · opcional')).toBeEnabled();
  await page.getByRole('button', { name: 'Revisar sequência' }).click();
  await expect(page.getByRole('heading', { name: 'Pronto para aplicar e enviar' })).toBeVisible();
  const isolation = await page.evaluate(() => ({ node: typeof (window as any).require, api: Object.keys(window.gitManager) }));
  expect(isolation.node).toBe('undefined'); expect(isolation.api).not.toContain('runGitCommand');
  const error = await page.evaluate(async () => { try { await window.gitManager.status('not-a-valid-id'); return ''; } catch (e) { return (e as Error).message; } });
  expect(error).not.toBe('');
  await page.screenshot({ path: '.local/screenshots/cherry-pick.png', fullPage: true });
  expect(errors).toEqual([]);
});
test('Electron: primeiro uso sem pastas salvas', async () => {
  const data = await tempDirectory('empty-app-');
  const env: Record<string, string> = Object.fromEntries(Object.entries(process.env).filter((entry): entry is [string, string] => typeof entry[1] === 'string' && entry[0] !== 'ELECTRON_RUN_AS_NODE'));
  application = await electron.launch({ args: [path.resolve('.')], env: { ...env, RAMOS_TEST_DATA: data } });
  const page = await application.firstWindow();
  await expect(page.getByRole('heading', { name: 'Tudo começa com uma pasta' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Criar / Alterar ramo', exact: true })).toBeDisabled();
  await page.screenshot({ path: '.local/screenshots/primeiro-uso.png', fullPage: true });
});
