import { afterEach, expect, it } from 'vitest';
import { build as buildRenderer } from 'vite';
import { build as buildMain } from 'esbuild';
import { _electron as electron, expect as expectUI, type ElectronApplication } from '@playwright/test';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { change, fixture, git } from './helpers';
let desktopApp: ElectronApplication | undefined;
afterEach(async () => { await desktopApp?.close(); desktopApp = undefined; });

it('compila o aplicativo e executa seleção → cherry-pick → push na interface real', async () => {
  const previousEnvironment = process.env.NODE_ENV;
  process.env.NODE_ENV = 'production';
  try { await buildRenderer({ logLevel: 'warn', mode: 'production' }); }
  finally { process.env.NODE_ENV = previousEnvironment; }
  await buildMain({ entryPoints: { main: 'electron/main.ts', preload: 'electron/preload.ts' }, bundle: true, platform: 'node', format: 'cjs', target: 'node22', outdir: 'dist-electron', outExtension: { '.js': '.cjs' }, external: ['electron'] });
  expect(await readFile('dist/index.html', 'utf8')).toContain('./assets/');
  const f = await fixture(); const data = path.join(f.root, 'desktop-data'); const bin = path.join(f.root, 'bin');
  await change(f.repo, 'description.txt', 'description', 'Correção detalhada\n\nCorpo completo para revisão.');
  await git(f.repo, 'push');
  await mkdir(data); await mkdir(bin);
  await writeFile(path.join(data, 'settings.json'), JSON.stringify({ roots: [f.root] }));
  // An actual executable on PATH exercises the Windows command invocation without installing proprietary dependencies.
  if (process.platform === 'win32') await writeFile(path.join(bin, 'pman.cmd'), '@echo off\r\nif not "%1 %2"=="install -f" exit /b 2\r\necho Dependencias de teste instaladas\r\nexit /b 0\r\n');
  else await writeFile(path.join(bin, 'pman'), '#!/bin/sh\n[ "$1 $2" = "install -f" ] || exit 2\necho dependencies-installed\n', { mode: 0o755 });
  const env: Record<string, string> = Object.fromEntries(Object.entries(process.env).filter((entry): entry is [string, string] => typeof entry[1] === 'string' && entry[0] !== 'ELECTRON_RUN_AS_NODE'));
  const pathKey = Object.keys(env).find(k => k.toUpperCase() === 'PATH') ?? 'PATH'; env[pathKey] = bin + path.delimiter + (env[pathKey] ?? '');
  let app: ElectronApplication | undefined;
  try {
    app = await electron.launch({ args: [path.resolve('.')], env: { ...env, RAMOS_TEST_DATA: data }, timeout: 20000 });
    desktopApp = app;
    const page = await app.firstWindow(); const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
    page.setDefaultTimeout(10000);
    page.setDefaultNavigationTimeout(10000);
    await expectUI(page.getByRole('heading', { name: 'Seus projetos', exact: true })).toBeVisible();
    await page.getByRole('button', { name: /work.*Abrir projeto/ }).click();
    await expectUI(page.locator('.branch-badge')).toContainText(f.source);
    await expectUI(page.getByRole('radio')).toHaveCount(3);
    await page.screenshot({ path: '.local/screenshots/switch.png', fullPage: true });
    await page.getByRole('button', { name: 'Histórico', exact: true }).click();
    await page.getByRole('button', { name: /Segunda alteração/ }).click();
    await expectUI(page.locator('.diff')).toContainText('+origem');
    await page.getByRole('button', { name: 'Cherry-pick', exact: true }).click();
    await expectUI(page.getByLabel('Destino 2 · opcional')).toBeDisabled();
    await page.getByLabel('Ramo de origem', { exact: true }).fill(f.source);
    await page.getByRole('button', { name: 'Carregar commits', exact: true }).click();
    await page.getByRole('checkbox', { name: 'Selecionar Primeira alteração' }).check();
    await page.getByLabel('Destino 1 · obrigatório').fill('main');
    await page.getByLabel('Destino 2 · opcional').fill('dev');
    await page.getByRole('button', { name: 'Revisar sequência' }).click();
    await expectUI(page.getByRole('heading', { name: 'Pronto para aplicar e enviar' })).toBeVisible();
    await page.screenshot({ path: '.local/screenshots/cherry-review.png', fullPage: true });
    await page.getByRole('button', { name: 'Aplicar commits e fazer push' }).click();
    await expectUI(page.getByRole('heading', { name: 'Última sequência concluída' })).toBeVisible({ timeout: 30000 });
    await expectUI(page.getByText('Push concluído', { exact: true })).toHaveCount(2);
    expect(await git(f.remote, 'show', 'main:first.txt')).toBe('primeiro');
    expect(await git(f.remote, 'show', 'dev:first.txt')).toBe('primeiro');
    expect(await git(f.remote, 'rev-parse', 'release')).toBe(f.base);
    const isolated = await page.evaluate(() => ({ require: typeof (window as any).require, methods: Object.keys(window.gitManager) }));
    expect(isolated.require).toBe('undefined'); expect(isolated.methods).not.toContain('runGitCommand');
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: '.local/screenshots/cherry-completed.png', fullPage: true });
    // Reapplying the same commit produces the empty cherry-pick reported by users.
    await page.getByRole('button', { name: 'Revisar sequência' }).click();
    await page.getByRole('button', { name: 'Aplicar commits e fazer push' }).click();
    await expectUI(page.getByRole('heading', { name: 'Sequência pendente' })).toBeVisible({ timeout: 30000 });
    await expectUI(page.getByRole('button', { name: 'Revisar sequência' })).toBeDisabled();
    await page.getByRole('button', { name: 'Cancelar sequência', exact: true }).click();
    await expectUI(page.getByRole('heading', { name: 'Última sequência cancelada' })).toBeVisible();
    await expectUI(page.getByRole('button', { name: 'Revisar sequência' })).toBeEnabled();
    expect(JSON.parse(await readFile(path.join(data, 'executions.json'), 'utf8'))[0].cancelledAt).toBeTruthy();
    await page.getByLabel('Destino 2 · opcional').fill('');
    await page.getByLabel('Destino 1 · obrigatório').fill('release');
    await page.getByRole('button', { name: 'Revisar sequência' }).click();
    await page.getByRole('button', { name: 'Aplicar commits e fazer push' }).click();
    await expectUI(page.getByRole('heading', { name: 'Última sequência concluída' })).toBeVisible({ timeout: 30000 });
    expect(await git(f.remote, 'show', 'release:first.txt')).toBe('primeiro');
    // The test uses an isolated credential helper and a mocked REST response; no real Azure account is accessed.
    const azureWeb = 'https://totvstfs.visualstudio.com/Linha-Winthor/_git/VA41-PCSIS4139';
    const helper = path.join(f.root, 'test-credential.cjs');
    await writeFile(helper, 'process.stdout.write("username=test\\npassword=fixture-only\\n");');
    await git(f.repo, 'config', '--local', 'credential.helper', '');
    await git(f.repo, 'config', '--local', '--add', 'credential.helper', `!node "${helper.replaceAll('\\', '/')}"`);
    await git(f.repo, 'remote', 'set-url', 'origin', azureWeb);
    await git(f.repo, 'config', '--local', `url.${f.remote.replaceAll('\\', '/')}.insteadOf`, azureWeb);
    await app.evaluate(({ shell }) => {
      (globalThis as any).testOpenedLinks = [];
      shell.openExternal = async url => { (globalThis as any).testOpenedLinks.push(url); };
      (globalThis as any).testCreatedPrs = [];
      globalThis.fetch = async (input, options) => {
        const url = new URL(String(input));
        if (url.hostname !== 'totvstfs.visualstudio.com' || !url.pathname.endsWith('/pullrequests')) throw new Error('Unexpected test URL');
        const saved = (globalThis as any).testCreatedPrs as any[];
        if (options?.method === 'POST') {
          const body = JSON.parse(String(options.body));
          const created = { ...body, pullRequestId: [870183, 870188, 870198][saved.length], status: 'active' };
          saved.push(created); return Response.json(created, { status: 201 });
        }
        return Response.json({ value: saved.filter(pr => pr.sourceRefName === url.searchParams.get('searchCriteria.sourceRefName') && pr.targetRefName === url.searchParams.get('searchCriteria.targetRefName')) });
      };
    });
    await page.getByRole('button', { name: 'Criar pull request', exact: true }).click();
    await page.getByRole('textbox', { name: 'Issue Jira opcional', exact: true }).fill('https://jiraproducao.totvs.com.br/browse/DDVENDAS-61611');
    await page.getByLabel('PR dinâmico').check();
    await page.getByLabel('Origem (1)', { exact: true }).fill(f.source);
    await page.getByLabel('Destino (1)', { exact: true }).fill('main');
    await page.getByRole('button', { name: '+ Adicionar pull request', exact: true }).click();
    await page.getByLabel('Destino (2)', { exact: true }).fill('dev');
    await page.getByRole('button', { name: '+ Adicionar pull request', exact: true }).click();
    await page.getByLabel('Destino (3)', { exact: true }).fill('release');
    await page.getByRole('button', { name: 'Buscar PRs e gerar mensagem', exact: true }).click();
    await expectUI(page.getByText(/PR ainda não encontrado:/)).toBeVisible();
    await expectUI(page.getByRole('button', { name: 'Copiar mensagem', exact: true })).toHaveCount(0);
    await page.getByRole('textbox', { name: 'Issue Jira opcional', exact: true }).fill('   ');
    await page.getByRole('button', { name: 'Criar 3 pull requests no Azure', exact: true }).click();
    const missingIssue = page.getByRole('dialog', { name: 'Issue Jira não informada', exact: true });
    await expectUI(missingIssue).toBeVisible();
    expect(await app.evaluate(() => (globalThis as any).testCreatedPrs.length)).toBe(0);
    await missingIssue.getByRole('button', { name: 'Voltar e preencher' }).click();
    await expectUI(missingIssue).not.toBeVisible();
    await expectUI(page.getByRole('textbox', { name: 'Issue Jira opcional', exact: true })).toBeFocused();
    await page.getByRole('textbox', { name: 'Issue Jira opcional', exact: true }).fill('DDVENDAS-61611');
    await page.getByRole('button', { name: 'Criar 3 pull requests no Azure', exact: true }).click();
    await expectUI(page.getByLabel('Prévia da mensagem')).toContainText('DDVENDAS-61611');
    const createdPrs = await app.evaluate(() => (globalThis as any).testCreatedPrs);
    expect(createdPrs).toHaveLength(3);
    for (const pr of createdPrs) {
      expect(pr.description).toContain('- Segunda alteração');
      expect(pr.description).toContain('- Correção detalhada\n  \n  Corpo completo para revisão.');
      expect(pr.isDraft).toBe(false);
    }
    await expectUI(page.getByLabel('Issue Jira', { exact: false }).filter({ visible: true })).toHaveValue('');
    await expectUI(page.getByLabel('Origem (1)', { exact: true })).toHaveValue('');
    await expectUI(page.getByLabel('Destino (1)', { exact: true })).toHaveValue('');
    await expectUI(page.getByLabel('Destino (2)', { exact: true })).toHaveCount(0);
    await expectUI(page.getByLabel('Prévia da mensagem')).toContainText(`main: ${azureWeb}/pullrequest/870183`);
    await expectUI(page.getByLabel('Prévia da mensagem')).toContainText(`dev: ${azureWeb}/pullrequest/870188`);
    await page.getByLabel('Prévia da mensagem').getByRole('link', { name: `${azureWeb}/pullrequest/870183`, exact: true }).click();
    await expect.poll(() => app!.evaluate(() => (globalThis as any).testOpenedLinks)).toEqual([`${azureWeb}/pullrequest/870183`]);
    await page.getByRole('button', { name: 'Copiar mensagem', exact: true }).click();
    await expectUI(page.getByText('Mensagem copiada com o link formatado do Jira. Cole no Google Chat com Ctrl+V.', { exact: true })).toBeVisible();
    const copied = await app.evaluate(({ clipboard }) => ({ text: clipboard.readText(), html: clipboard.readHTML() }));
    expect(copied.html).toContain('href="https://jiraproducao.totvs.com.br/browse/DDVENDAS-61611">DDVENDAS-61611</a>');
    expect(copied.text).toContain(`main: ${azureWeb}/pullrequest/870183`);
    const savedReviews = JSON.parse(await readFile(path.join(data, 'review-messages.json'), 'utf8'));
    expect(savedReviews).toHaveLength(1); expect(savedReviews[0].issue.key).toBe('DDVENDAS-61611');
    await page.getByLabel('Buscar no histórico').fill('DDVENDAS-61611');
    await page.getByRole('button', { name: 'Alterar issue do jira', exact: true }).click();
    const issueDialog = page.getByRole('dialog');
    await expectUI(issueDialog.getByLabel('Issue Jira')).toHaveValue('DDVENDAS-61611');
    await issueDialog.getByLabel('Issue Jira').fill('inválido');
    await issueDialog.getByRole('button', { name: 'Salvar issue' }).click();
    await expectUI(issueDialog.getByRole('alert')).toBeVisible();
    await issueDialog.getByLabel('Issue Jira').fill('');
    await issueDialog.getByRole('button', { name: 'Salvar issue' }).click();
    await expectUI(issueDialog).not.toBeVisible();
    await expectUI(page.getByLabel('Prévia da mensagem')).not.toContainText('DDVENDAS-61611');
    await page.getByRole('button', { name: 'Copiar mensagem', exact: true }).click();
    await expectUI(page.getByRole('button', { name: 'Copiar mensagem', exact: true })).toBeEnabled();
    expect(await app.evaluate(({ clipboard }) => clipboard.readText())).not.toContain('Tarefa disponível para revisão');
    await page.getByLabel('Buscar no histórico').fill('Sem issue');
    await page.getByRole('button', { name: 'Adicionar issue', exact: true }).click();
    await issueDialog.getByLabel('Issue Jira').fill('DDVENDAS-70001');
    await issueDialog.getByRole('button', { name: 'Salvar issue' }).click();
    await expectUI(issueDialog).not.toBeVisible();
    await expectUI(page.getByLabel('Prévia da mensagem')).toContainText('DDVENDAS-70001');
    await page.getByLabel('Buscar no histórico').fill('DDVENDAS-70001');
    await page.getByRole('button', { name: 'Copiar mensagem anterior', exact: true }).click();
    await expectUI(page.getByText('Mensagem do histórico copiada com a saudação do horário atual. Cole no Google Chat com Ctrl+V.', { exact: true })).toBeVisible();
    expect(await app.evaluate(({ clipboard }) => clipboard.readHTML())).toContain('>DDVENDAS-70001</a>');
    expect(JSON.parse(await readFile(path.join(data, 'review-messages.json'), 'utf8'))[0].issue.key).toBe('DDVENDAS-70001');
    await page.screenshot({ path: '.local/screenshots/review-message.png', fullPage: true });
    await page.getByLabel('PR dinâmico').uncheck();
    await page.getByLabel('Origem (seu ramo)', { exact: true }).fill(f.source);
    await page.getByLabel('Destino', { exact: true }).fill('main');
    await page.getByRole('button', { name: 'Criar pull request no Azure', exact: true }).click();
    await expectUI(missingIssue).toBeVisible();
    await missingIssue.getByRole('button', { name: 'Prosseguir sem issue' }).click();
    await expectUI(missingIssue).not.toBeVisible();
    await expectUI(page.getByText(/0 PR\(s\) criado\(s\), 1 já existente\(s\)/)).toBeVisible();
    await expectUI(page.getByLabel('Prévia da mensagem')).not.toContainText('Tarefa disponível para revisão');
    expect(errors).toEqual([]);
  } catch (error) {
    await app?.windows()[0]?.screenshot({ path: '.local/screenshots/desktop-failure.png', fullPage: true }).catch(() => {});
    throw error;
  } finally { await app?.close(); }
}, 90000);
